<a href="https://colab.research.google.com/github/24f2002727/Machine-learning-models/blob/main/dream11-data-analysis-model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
bat_data=pd.read_csv("/content/Batting_data.csv")
bat_data.head()

,match_id,season,match_name,home_team,away_team,venue,bowling_team,batting_team,batting_innings,fullName,batting_position,runs,balls,fours,sixes,strike_rate,Batting_FP
0,1359475,2023,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,CSK,1,Devon Conway,1,1,6,0,0,16.66,1
1,1359475,2023,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,CSK,1,Ruturaj Gaikwad,2,92,50,4,9,184.00,128
2,1359475,2023,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,CSK,1,Moeen Ali,3,23,17,4,1,135.29,31
3,1359475,2023,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,CSK,1,Ben Stokes,4,7,6,1,0,116.66,8
4,1359475,2023,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,CSK,1,Ambati Rayudu,5,12,12,0,1,100.00,14

In [ ]:
field_data=pd.read_csv("/content/Fielding_data.csv")
field_data.head()

,season,match_id,match_name,home_team,away_team,venue,batting_team,bowling_innings,bowling_team,fullName,catching_FP,stumping_FP,direct_runout_FP,indirect_runout_FP,Fielding_FP
0,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,1,CSK,MS Dhoni,8,12,0,0,20
1,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,1,CSK,Ruturaj Gaikwad,8,0,0,0,8
2,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",CSK,2,GT,David Miller,8,0,0,0,8
3,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",CSK,2,GT,Mohit Sharma,8,0,0,0,8
4,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",CSK,2,GT,Rashid Khan,8,0,0,0,8

In [ ]:
final_data=pd.read_csv("/content/Final_Fantasy_data.csv")
final_data.head()

,season,match_id,match_name,home_team,away_team,venue,batting_innings,bowling_innings,fullName,Starting_11,Batting_FP,Bowling_FP,Fielding_FP,Total_FP,Dream Team,Captain,Vice Captain
0,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",1,2,Sai Sudharsan,4,130,0,0,134,1,1,0
1,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",1,2,Mohit Sharma,4,0,83,8,95,1,0,1
2,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",1,2,Wriddhiman Saha,4,71,0,0,75,1,0,0
3,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",1,2,Shubman Gill,4,56,0,0,60,1,0,0
4,2023,1370353,GT v CSK,GT,CSK,"Narendra Modi Stadium, Motera, Ahmedabad",1,2,Noor Ahmad,4,0,54,0,58,1,0,0

In [ ]:
bow_data=pd.read_csv("/content/Bowling_data.csv")
bow_data.head()

,season,match_id,match_name,home_team,away_team,batting_team,bowling_team,venue,bowling_innings,fullName,...,wickets,economyRate,wides,noballs,LBW,Hitwicket,CaughtBowled,Bowled,Overs_Bowled,Bowling_FP
0,2023,1359475,GT v CSK,GT,CSK,CSK,GT,"Narendra Modi Stadium, Motera, Ahmedabad",1,Mohammed Shami,...,2,7.25,0,1,0,0,0,1,"[1, 3, 5, 19]",58
1,2023,1359475,GT v CSK,GT,CSK,CSK,GT,"Narendra Modi Stadium, Motera, Ahmedabad",1,Hardik Pandya,...,0,9.33,0,0,0,0,0,0,"[2, 7, 15]",0
2,2023,1359475,GT v CSK,GT,CSK,CSK,GT,"Narendra Modi Stadium, Motera, Ahmedabad",1,Josh Little,...,1,10.25,0,0,0,0,0,1,"[4, 11, 13, 20]",31
3,2023,1359475,GT v CSK,GT,CSK,CSK,GT,"Narendra Modi Stadium, Motera, Ahmedabad",1,Rashid Khan,...,2,6.50,0,0,0,0,0,0,"[6, 8, 10, 17]",52
4,2023,1359475,GT v CSK,GT,CSK,CSK,GT,"Narendra Modi Stadium, Motera, Ahmedabad",1,Alzarri Joseph,...,2,8.25,0,0,0,0,0,0,"[9, 14, 16, 18]",50

In [ ]:
match_data=pd.read_csv("/content/Match_details.csv")
match_data.head()

,match_id,season,match_name,venue,home_team,away_team
0,1359475,2023,GT v CSK,"Narendra Modi Stadium, Motera, Ahmedabad",GT,CSK
1,1359476,2023,PBKS v KKR,"Punjab Cricket Association IS Bindra Stadium, ...",PBKS,KKR
2,1359477,2023,LSG v DC,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,LSG,DC
3,1359478,2023,SRH v RR,"Rajiv Gandhi International Stadium, Uppal, Hyd...",SRH,RR
4,1359479,2023,RCB v MI,"M.Chinnaswamy Stadium, Bengaluru",RCB,MI

In [ ]:
data=pd.read_csv("/content/data.csv")
data.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [ ]:
#Top batters code
top_batters=(bat_data.groupby('fullName')['runs'].sum().sort_values(ascending=False).reset_index().head(10))
print(top_batters)

         fullName  runs
0     Virat Kohli  7263
1  Shikhar Dhawan  6617
2    David Warner  6397
3    Rohit Sharma  6211
4    Suresh Raina  5528
5  AB de Villiers  5162
6        MS Dhoni  5082
7     Chris Gayle  4965
8   Robin Uthappa  4952
9  Dinesh Karthik  4516

In [ ]:
#Top bowlers
top_bowlers=(bow_data.groupby('fullName')['wickets'].sum().sort_values(ascending=False).reset_index().head(10))
print(top_bowlers)

              fullName  wickets
0     Yuzvendra Chahal      187
1         Dwayne Bravo      183
2        Piyush Chawla      179
3          Amit Mishra      173
4  Ravichandran Ashwin      171
5       Lasith Malinga      170
6    Bhuvneshwar Kumar      170
7         Sunil Narine      163
8      Ravindra Jadeja      152
9      Harbhajan Singh      150

In [ ]:
#Top fielders
top_fielders=(field_data.groupby('fullName')['Fielding_FP'].sum().sort_values(ascending=False).reset_index().head(10))
print(top_fielders)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7ae8a5aaa290>

In [ ]:
#Top Fantasy player
fantaty_player=(final_data.groupby('fullName')['Total_FP'].sum().sort_values(ascending=False).reset_index().head(20))
print(fantaty_player)

               fullName  Total_FP
0           Virat Kohli     11310
1          Rohit Sharma     10342
2        Shikhar Dhawan     10233
3          David Warner      9873
4          Suresh Raina      9743
5       Ravindra Jadeja      9711
6              MS Dhoni      9647
7        AB de Villiers      8777
8          Shane Watson      8682
9        Dinesh Karthik      8649
10        Robin Uthappa      8643
11         Dwayne Bravo      8320
12          Chris Gayle      8101
13       Kieron Pollard      8019
14         Sunil Narine      7383
15  Ravichandran Ashwin      7135
16        Piyush Chawla      7043
17        Ambati Rayudu      6989
18       Ajinkya Rahane      6850
19         Sanju Samson      6680